[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[build.args]
NODE_ENV = "production"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10