[build]
builder = "dockerfile"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[build.args]
NODE_ENV = "production"

# Ensure environment variables are passed to the container
[build]
dockerfilePath = "Dockerfile"